version: '3'
services:
    tomcat:
        image: brightspot/tomcat:8.5.69-jdk8
        hostname: task.brightspot
        ports:
            - 5005:5005
        volumes:
            - .:/code:cached
            - ~/.aws/credentials:/etc/aws/credentials:cached
            - storage-data:/servers/tomcat/storage
        environment:
            - ROOT_WAR=/code/target/base-brightspot-1.0-SNAPSHOT.war
            - CONTEXT_PROPERTIES=/code/docker-context.properties
            - LOGGING_PROPERTIES=/code/docker-logging.properties
            #- TEMPLATE_CONFIG=/code/docker-template.yml
    solr:
        image: brightspot/solr:4
        ports:
            - 8081:8080
        volumes:
            - solr-data:/servers/tomcat/solr/collection1/data
    apache:
        image: brightspot/apache:2-dims3
        ports:
            - 80:80
            - 443:443
        volumes:
            - storage-data:/var/www/localhost/htdocs/storage
    mysql:
        image: brightspot/mysql:mysql5.6
        ports:
            - 3306:3306
        volumes:
            - mysql-data:/var/lib/mysql
            - mysql-logs:/var/log/mysql
    greenmail:
        image: greenmail/standalone:1.6.11
        ports:
            - 3025:3025
            - 3110:3110
            - 3143:3143
            - 3465:3465
            - 3993:3993
            - 3995:3995
volumes:
    mysql-data:
    mysql-logs:
    solr-data:
    storage-data:
